DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS salt;
CREATE TABLE salt
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Salt          BINARY VARYING(255),
    PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Email        VARCHAR(255),
    Name         VARCHAR(255),
    Password     VARCHAR(255),
    Role         ENUM('admin', 'user', 'guest'),
    Surname      VARCHAR(255),
    Username     VARCHAR(255),
    HashPassword VARCHAR(255),
    saltid                  INTEGER,

    PRIMARY KEY (id),
    FOREIGN KEY (saltid) REFERENCES salt(id)
);




CREATE TABLE tests
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    userId                  INTEGER,
    questionIdList          VARCHAR(255),
    userChosenAnswerList    VARCHAR(255),
    score                   INTEGER,
    topic                   ENUM('random', 'signs','driving_priority'),
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE questions
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    topic           ENUM('random', 'signs', 'driving_priority'),
    question        VARCHAR(255),
    answers         VARCHAR(255),
    correctAnswers  VARCHAR(255),
    PRIMARY KEY (id)
);

